form/urls.py
from tkinter.font import names

from django.urls import path
from . import views

#sao para onde eles sao redirecionados
urlpatterns = [
    path('', views.acesso, name='acesso'),
    path('formulario/', views.formulario, name='formulario'),
    path('processa_formulario/', views.processa_formulario, name ="processa_formulario"),
    path('pessoa/<int:pessoa_id>/', views.envio_formulario, name='envio_formulario'),
    path('lista/', views.PessoaList.as_view(), name='pessoa-lista'),
    path('update/<int:pk>/', views.PessoaUpdate.as_view(), name='pessoa-update'),
    path('detail/<int:pk>/', views.PessoaDetail.as_view(), name='pessoa-detail'),
    path('delete/<int:pk>/', views.delete_pessoa , name='pessoa-delete'),
    path('login/', views.login, name='login'),
]

mysite/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('form.urls')),
    path('admin/', admin.site.urls),
]

form/models.py
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models

#criação das tabelas (banco de dados)

class Contato(models.Model):
        email = models.EmailField(help_text='exemplo@email.com', unique=True)
        telefone = models.CharField(
            max_length=15,
            unique= True,
            validators=[
                RegexValidator(regex=r'^\d{10,15}$', message='O número de telefone deve conter apenas dígitos.')]
        )
        cidade = models.CharField(max_length=80)
        endereco = models.CharField(max_length=50)
        numero = models.IntegerField()

        def __str__(self):
            return self.email

class Pessoa(models.Model):
        nome = models.CharField(max_length=100, help_text='nome completo')
        data_nascimento = models.DateField()
        GENEROS = [
            ('Masculino', 'Masculino'),
            ('Feminino', 'Feminino'),
            ('Não-binário', 'Não-binário'),
            ('Outro', 'Outro'),
            ('Prefiro não dizer', 'Prefiro não dizer'),
        ]
        genero = models.CharField(max_length=20, choices=GENEROS)
        criado_em = models.DateTimeField(auto_now_add=True)
        contato = models.OneToOneField(Contato, on_delete=models.CASCADE, related_name='pessoa')


        def __str__(self):
            return self.nome

class Experiencia(models.Model):
        empresa = models.CharField(max_length=50)
        cargo = models.CharField(max_length=50)
        duracao = models.CharField(max_length=20)
        resumo = models.TextField(max_length=1000)
        pessoa = models.ManyToManyField(Pessoa, related_name='experiencias')


        def __str__(self):
            return self.empresa




class Formacao(models.Model):
        instituicao = models.CharField(max_length=50)
        curso = models.CharField(max_length=50)
        periodo = models.CharField(max_length=50)
        pessoa = models.ManyToManyField(Pessoa, related_name='formacoes')

        def __str__(self):
            return self.instituicao

form/forms.py
from django import forms
from .models import Pessoa, Contato, Experiencia, Formacao
from django.forms import modelformset_factory




class formularioContato(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ('email', 'telefone','cidade', 'endereco', 'numero')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;', 'placeholder': 'exemplo@email.com'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;', 'placeholder': '(xx)xxxxx-xxxx'}),
            'cidade': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'endereco': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'numero': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
        }
        def clean_email(self):
            email = self.cleaned_data.get('email')
            if Contato.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError("Este email já está em uso.")
            return email

        def clean_telefone(self):
            telefone = self.cleaned_data.get('telefone')
            if Contato.objects.filter(telefone=telefone).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError("Este telefone já está em uso.")
            return telefone

class formularioCadastro(forms.ModelForm):
    class Meta:
        model = Pessoa
        fields = ('nome', 'data_nascimento', 'genero')
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;', 'placeholder': 'Nome completo'}),
            'data_nascimento': forms.DateInput(format='%d-%m-%y', attrs={'class': 'form-control-sm', 'type': 'date', 'style': 'border-radius: 10px;'}),
        }

class formularioExperiencia(forms.ModelForm):
    class Meta:
        model = Experiencia
        fields = ('empresa', 'cargo', 'duracao', 'resumo')
        widgets = {
            'empresa': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'cargo': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'duracao': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'resumo': forms.TextInput(attrs={'class': 'form-control-sm','style': 'border-radius: 10px;'}),
        }

class formularioFormacao(forms.ModelForm):
    class Meta:
        model = Formacao
        fields = ('instituicao', 'curso', 'periodo')
        widgets = {
            'instituicao': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'curso': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
            'periodo': forms.TextInput(attrs={'class': 'form-control-sm', 'style': 'border-radius: 10px;'}),
        }

ExperienciaFormSet = modelformset_factory(Experiencia, form=formularioExperiencia, extra=1)
FormacaoFormSet = modelformset_factory(Formacao, form=formularioFormacao, extra=1)

form/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .forms import formularioCadastro, formularioContato, formularioExperiencia, formularioFormacao, ExperienciaFormSet, FormacaoFormSet
from .models import Pessoa, Contato, Experiencia, Formacao
from django.contrib.auth.mixins import LoginRequiredMixin


def acesso(request):
        return render(request, 'form/acesso.html')


#chama os formularios
def formulario(request):
        form = formularioCadastro()
        formc = formularioContato()
        forme = ExperienciaFormSet(queryset=Experiencia.objects.none())
        formf = FormacaoFormSet(queryset=Formacao.objects.none())
        return render(request, 'form/formulario.html', {'form': form, 'formc': formc, 'forme':forme, 'formf': formf}, )

#salva as informações
def processa_formulario(request):
    if request.method == 'POST':
        form = formularioCadastro(request.POST)
        formc = formularioContato(request.POST)
        forme = ExperienciaFormSet(request.POST)
        formf = FormacaoFormSet(request.POST)

        if form.is_valid() and formc.is_valid() and forme.is_valid() and formf.is_valid():
            contato = formc.save()
            pessoa = form.save(commit=False)
            pessoa.contato = contato
            pessoa.save()

            experiencias = forme.save(commit=False)
            for experiencia in experiencias:
                experiencia.save()
                pessoa.experiencias.add(experiencia)

            formacoes = formf.save(commit=False)
            for formacao in formacoes:
                formacao.save()
                pessoa.formacoes.add(formacao)


            return redirect('envio_formulario', pessoa_id=pessoa.id)
        else:
            return render(request, 'form/formulario.html', {'form': form, 'formc': formc, 'forme':forme, 'formf': formf}, )

    return HttpResponse('Método de requisição inválido')


#direciona para mostrar os dados salvos
def envio_formulario(request, pessoa_id):
    pessoa = get_object_or_404(Pessoa, id=pessoa_id)
    return render(request, 'form/envio.html', {'pessoa': pessoa})


#uma class based view para a lista
class PessoaList(LoginRequiredMixin, ListView):
    model = Pessoa
    queryset = Pessoa.objects.all()

#class based view para mostrar todas as infos do candidato
class PessoaDetail(LoginRequiredMixin, DetailView):
    model = Pessoa
    queryset = Pessoa.objects.all()

#class based view para atualizar as infos
class PessoaUpdate(LoginRequiredMixin, UpdateView):
    model = Pessoa
    fields = '__all__'
    success_url = reverse_lazy('pessoa-lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['forme'] = formularioExperiencia(self.request.POST, instance=self.object.experiencias.first())
            context['formf'] = formularioFormacao(self.request.POST, instance=self.object.formacoes.first())
            context['formc'] = formularioContato(self.request.POST, instance=self.object.contato)
        else:
            context['forme'] = formularioExperiencia(instance=self.object.experiencias.first())
            context['formf'] = formularioFormacao(instance=self.object.formacoes.first())
            context['formc'] = formularioContato(instance=self.object.contato)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        forme = context['forme']
        formf = context['formf']
        formc = context['formc']

        if forme.is_valid() and formf.is_valid() and formc.is_valid():
            form.save()
            formc.save()
            forme.save()
            formf.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

#function based view para deletar as informações pelo id da pessoa
def delete_pessoa(request, pk):
    try:
        pessoa = get_object_or_404(Pessoa, id=pk)
        print(f"Pessoa: {pessoa}")

        experiencia_ids = pessoa.experiencias.values_list('id', flat=True)
        print(f"Experiencia IDs: {experiencia_ids}")

        formacao_ids = pessoa.formacoes.values_list('id', flat=True)
        print(f"Formacao IDs: {formacao_ids}")

        Experiencia.objects.filter(id__in=experiencia_ids).delete()
        Formacao.objects.filter(id__in=formacao_ids).delete()
        pessoa.contato.delete()
        pessoa.delete()
        print(f"Pessoa {pk} deletada com sucesso!")

        return redirect('pessoa-lista')
    except Exception as e:
        print(f"Erro ao deletar: {e}")
        return redirect('pessoa-lista')

#login para entrar na lista e sua funções
def login(request):
    if request.method == "GET":
        return render(request, 'form/login.html')
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = authenticate(username=username, password=senha)

        if user:
            login_django(request, user)

            return render(request, 'form/abrirlista.html')
        else:
            return render(request, 'form/login.html')

form/templates/form/abrirlista.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
    <title>Abrir lista</title>
</head>
<body>
    <form>
        <img src="{% static 'imagens/lista.png' %}" class="abrirlista">
    <a href="{% url 'pessoa-lista' %}" class="btn btn-primary buttons abrirlista" >LISTA</a></button>
    </form>
</body>
</html>

form/templates/form/acesso.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0&icon_names=description" />
    <title>Login</title>
</head>
    <body>
        <form>
             <h1 class="pegho">PEGHO</h1>

            <div class="il">
                <img src="{% static 'imagens/candidato.png' %}">
                <img src="{% static 'imagens/recrutador.png' %}">
            </div>
                <div>
                    <a href="{% url 'formulario' %}" class="btn btn-primary buttons">CANDIDATAR-SE</a></button>
                    <a href="{% url 'login' %}" class="btn btn-primary buttons">RECRUTADOR</a></button>
                </div>
        </form>
    </body>
</html>

form/templates/form/envio.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes da Pessoa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <a href="{% url 'acesso' %}" class="btn btn-warning voltar">VOLTAR INICIO</a>
    <a href="{% url 'login' %}" class="btn btn-warning voltarlista">RECRUTADOR - LISTA</a>
    <div class="container">
        <form>
            <h1 class="info">Detalhes da Pessoa: {{ pessoa.nome }}</h1>
                <p><strong>Data de Nascimento:</strong> {{ pessoa.data_nascimento }}</p>
                <p><strong>Gênero:</strong> {{ pessoa.get_genero_display }}</p>
                <p><strong>Email:</strong> {{ pessoa.contato.email }}</p>
                <p><strong>Telefone:</strong> {{ pessoa.contato.telefone }}</p>
                <p><strong>Cidade:</strong> {{ pessoa.contato.cidade }}</p>
                <p><strong>Endereço:</strong> {{ pessoa.contato.endereco }}, {{ pessoa.contato.numero }}</p>

            <h2>Experiências Profissionais</h2>
                <ul>
                    {% for experiencia in pessoa.experiencias.all %}
                        <li>{{ experiencia.empresa }} - {{ experiencia.cargo }} ({{ experiencia.duracao }}): {{ experiencia.resumo }}</li>
                    {% endfor %}
                </ul>

            <h2>Formação</h2>
                <ul>
                {% for formacao in pessoa.formacoes.all %}
                    <li>{{ formacao.instituicao }} - {{ formacao.curso }} ({{ formacao.periodo }})</li>
                {% endfor %}
            </ul>
        </form>
    </div>
    <div>
        <form class="bg-success">
            <h1 class="agradece">PEGHO</h1>
            <p class="agradece">Agradecemos o seu interesse e participação.</p>
        </form>
    </div>
</body>
</html>

form/templates/form/formulario.html
<!doctype html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
    <script src="{% static 'js/java.js' %}"></script>
    <title>Formulario</title>
  </head>
  <header>
    <h1>FORMULARIO</h1>
  </header>
  <body>
  <a href="{% url 'acesso' %}" class="btn btn-warning voltar">VOLTAR</a>
  <form action="{% url 'processa_formulario' %}" method="POST">{% csrf_token %}
    <div>
      <h2>Dados pessoais</h2>
    </div>
    <hr>
    <div class="container">
      <div class="centralizar">
        <label>Nome: </label>
          {{form.nome}}
            {% if form.nome.errors %}
              <div>
                {{ form.nome.errors }}
              </div>
            {% endif %}
      </div>
    <div class="centralizar">
        <label>Data de Nascimento: </label>
          {{form.data_nascimento}}
            {% if form.data_nascimento.errors %}
              <div>
                {{ form.data_nascimento.errors }}
              </div>
            {% endif %}
    </div>
    <div class="centralizar">
        <label>Genero: </label>
          {{form.genero}}
            {% if form.genero.errors %}
              <div class="error">
                {{ form.genero.errors }}
              </div>
            {% endif %}
    </div>
    <div class="centralizar">
        <label>Email: </label>
          {{formc.email}}
            {% if formc.email.errors %}
              <div class="error">
                {{ formc.email.errors }}
              </div>
            {% endif %}
    </div>
    <div class="centralizar">
        <label>Telefone: </label>
          {{formc.telefone}}
            {% if formc.telefone.errors %}
              <div class="error">
                {{ formc.telefone.errors }}
              </div>
            {% endif %}
    </div>
    <div class="centralizar">
        <label>Cidade: </label>
          {{formc.cidade}}
            {% if formc.cidade.errors %}
              <div class="error">
                {{ formc.cidade.errors }}
              </div>
            {% endif %}
    </div>
    <div class="centralizar">
        <label>Endereço: </label>
          {{formc.endereco}}
            {% if formc.endereco.errors %}
              <div class="error">
                {{ formc.endereco.errors }}
              </div>
            {% endif %}
    </div>
    <div class="centralizar">
        <label>Numero: </label>
          {{formc.numero}}
            {% if formc.numero.errors %}
              <div class="error">
                {{ formc.numero.errors }}
              </div>
            {% endif %}
    </div>
    </div>


    <h3>Experiencia Profissional</h3>
    <hr>
    <div class="centralizar container">
        {{ forme.management_form }}
        <div>
            {% for form in forme %}
                <div>
                    {{ form.as_p }}
                </div>
            {% endfor %}
        </div>
    </div>

    <h3>Formação</h3>
    <hr>
      <div class="centralizar container">
          {{ formf.management_form }}
        <div>
          {% for form in formf %}
            <div>
              {{ form.as_p }}
            </div>
          {% endfor %}
        </div>
      </div>
    <div class="centralizar">
        <input class="btn btn-success envio" type="submit">
    </div>
  </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

form/templates/form/login.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
    <title>Login Recrutador</title>
</head>
<body>
    <a href="{% url 'acesso' %}" class="btn btn-warning voltar">VOLTAR</a>
    <form action="{% url 'login' %}" method="POST">{% csrf_token %}

        <label>Usuario:</label>
        <input type="text" placeholder="Username..." name="username">
        <label>Senha:</label>
        <input type="password" placeholder="senha..." name="senha">

        <input type="submit" value="logar" class="btn btn-success envio">
    </form>
</body>
</html>

form/templates/form/pessoa_confirm_delete.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes da Pessoa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <div class="container">
        <form>
            <h1 class="info">Detalhes da Pessoa: {{ pessoa.nome }}</h1>
                <p><strong>Data de Nascimento:</strong> {{ pessoa.data_nascimento }}</p>
                <p><strong>Gênero:</strong> {{ pessoa.get_genero_display }}</p>
                <p><strong>Email:</strong> {{ pessoa.contato.email }}</p>
                <p><strong>Telefone:</strong> {{ pessoa.contato.telefone }}</p>
                <p><strong>Cidade:</strong> {{ pessoa.contato.cidade }}</p>
                <p><strong>Endereço:</strong> {{ pessoa.contato.endereco }}, {{ pessoa.contato.numero }}</p>

            <h2>Experiências Profissionais</h2>
                <ul>
                    {% for experiencia in pessoa.experiencias.all %}
                        <li>{{ experiencia.empresa }} - {{ experiencia.cargo }} ({{ experiencia.duracao }}): {{ experiencia.resumo }}</li>
                    {% endfor %}
                </ul>

            <h2>Formação</h2>
                <ul>
                {% for formacao in pessoa.formacoes.all %}
                    <li>{{ formacao.instituicao }} - {{ formacao.curso }} ({{ formacao.periodo }})</li>
                {% endfor %}
            </ul>
        </form>
        <br>
        <form action="." method="post" class="formdel">
            {% csrf_token %}
                    <input class="btn btn-danger buttons aligndel" type="submit" value="APAGAR">
                    <a href="{% url 'pessoa-lista' %}" class="btn btn-primary buttons aligndel">NÃO APAGAR</a>
        </form>
    </div>
</body>
</html>

form/templates/form/pessoa_detail.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <form>
            <h1 class="info">Detalhes da Pessoa: {{ pessoa.nome }}</h1>
                <p><strong>Data de Nascimento:</strong> {{ pessoa.data_nascimento }}</p>
                <p><strong>Gênero:</strong> {{ pessoa.get_genero_display }}</p>
                <p><strong>Email:</strong> {{ pessoa.contato.email }}</p>
                <p><strong>Telefone:</strong> {{ pessoa.contato.telefone }}</p>
                <p><strong>Cidade:</strong> {{ pessoa.contato.cidade }}</p>
                <p><strong>Endereço:</strong> {{ pessoa.contato.endereco }}, {{ pessoa.contato.numero }}</p>

            <h2>Experiências Profissionais</h2>
                <ul>

                        {% for experiencia in pessoa.experiencias.all %}
                        <li>{{ experiencia.empresa }} - {{ experiencia.cargo }} ({{ experiencia.duracao }}): {{ experiencia.resumo }}</li>
                    {% endfor %}
                </ul>

            <h2>Formação</h2>
                <ul>
                {% for formacao in pessoa.formacoes.all %}
                    <li>{{ formacao.instituicao }} - {{ formacao.curso }} ({{ formacao.periodo }})</li>
                {% endfor %}
            </ul>
        </form>
        <a href="{% url 'pessoa-lista' %}" class="btn btn-primary detail">VOLTAR PARA LISTA</a></button>
    </div>
</body>
</html>

form/templates/form/pessoa_form.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <title>update</title>
</head>
<body>
    <h1>teste</h1>
    <form method="POST" action=".">
        {% csrf_token %}
        {{ form }}
        {{ formc }}
        {{ forme }}
        {{ formf }}

        <input type="submit" value="salvar">
    </form>
</body>
</html>

form/templates/form/pessoa_list.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <title>Lista</title>
</head>
<body>
    <a href="{% url 'acesso' %}" class="btn btn-warning voltar">VOLTAR</a>
    <form>
        <h1>Lista dos candidatos</h1>
            <ul>{% for pessoa in object_list %}
                <li class="liststyle">
                        {{ pessoa.nome }}
                    <a href="{% url 'pessoa-detail' pessoa.pk %}" class="btn btn-primary bdetail ">DETALHES</a>
                    <a href="{% url 'pessoa-update' pessoa.pk %}" class="btn btn-info bupdate">ATUALIZAR</a>
                    <a href="{% url 'pessoa-delete' pessoa.pk %}" class="btn btn-danger bdelete">APAGAR</a>
                </li>
                {% endfor %}
            </ul>
        <a href="{% url 'formulario' %}" class="btn btn-primary buttons addcand">ADICIONAR MAIS CANDIDATOS</a></button>
    </form>
</body>
</html>